/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'angus' at '10/11/16 10:06 PM' with Gradle 3.1
 *
 * @author angus, @date 10/11/16 10:06 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
//    def "someLibraryMethod returns true"() {
//        setup:
//        Library lib = new Library()
//        when:
//        def result = lib.someLibraryMethod()
//        then:
//        result == true
//    }
}
